# Generated by Django 3.2.4 on 2022-04-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_collection_c_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': '收藏信息管理', 'verbose_name_plural': '收藏信息管理'},
        ),
    ]
