# Generated by Django 3.2.4 on 2022-04-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='img',
        ),
        migrations.RemoveField(
            model_name='users',
            name='nick_name',
        ),
        migrations.AddField(
            model_name='users',
            name='college',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='用户所属学院'),
        ),
    ]
