# Generated by Django 3.2.4 on 2022-02-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbook',
            name='b_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='关联学科分类id'),
        ),
    ]
