# Generated by Django 3.2.4 on 2022-04-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclass', '0003_auto_20220409_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbook',
            name='b_id',
        ),
    ]
