# Generated by Django 3.2.4 on 2022-05-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclass', '0004_remove_tbook_b_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbook',
            options={'ordering': ['id'], 'verbose_name': '教材列表', 'verbose_name_plural': '教材列表'},
        ),
        migrations.AlterModelOptions(
            name='tpress',
            options={},
        ),
        migrations.AddField(
            model_name='tbook',
            name='p_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='学科id'),
        ),
    ]
